const mongoose =require('mongoose')
const userSchema =new mongoose.Schema(
    {
        razon_social: String,
        nit: String,
        nim_niar: String,
        nro_nim: String,
        tipo_operador: String,
        nro_personeria: String,
        nro_matricula_seprec: String,
        fecha_exp_seprec: String,
        tipo_doc_creacion: String,
        doc_creacion: String,
        departamento: String,
        municipio: String,
        direccion: String,
        ubicacion: String,
        correo_inst: String,
        tel_fijo: String,
        celular: String,
        celular_2: String,
        act_exploracion: String,
        act_comer_interna: String,
        act_comer_externa: String,
        act_industrializacion: String,
        act_tras_colas: String,
        act_explotacion: String,
        act_refinacion: String,
        act_fundicion: String,
        tipo_explotacion: String,
        denominacion_area: String,
        nro_codigo_unico: String,
        nro_cuadricula: String,
        municipio_origen: String,
        nro_ruex: String,
        verif_cert_liberacion: String,
        nro_res_ministerial: String,
        nombre_resp_for101: String,
        ci_resp_for101: String,
        celular_resp_for101: String,
        correo_resp_for101: String,
        nombre_resp_tmuestra: String,
        ci_resp_tmuestra: String,
        celular_resp_tmuestra: String,
        correo_resp_tmuestra: String,
    }
)
module.exports=mongoose.model('Operador', userSchema)
